### ISSUE TITLE
No drop shadow on thumbnails

### ISSUE THREAD

**Issue by kaetemi** [iOrange/QOIThumbnailProvider#1]
No drop shadow when following installation instructions, compare with PNG.

See https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/cc144118(v=vs.85)#thumbnail-adornments

![Thumbnails with no drop shadows on QOI files.](https://cdn.kaetemi.be/dl/git/qoi_thumb_nodrop.png)

**Comment by iOrange** [comment]
It's a personal preference, but yes, I can add that.

**Comment by iOrange** [comment]
Fixed with d1625c8.
Thanks!
