### ISSUE TITLE
doesn't work after reboot.

### ISSUE THREAD

**Issue by boris-999** [iOrange/QOIThumbnailProvider#2]
it worked as per instructions but after a reboto it no longer works.

explain the regsrv thing, what does it do, for how long, what makes it no longer work after a reboot?

does this regsrc copy the .dll to somewhere?  if not, make that clear that you have to copy it somewhere

**Comment by iOrange** [comment]
Hi!

The dll you register has to stay in that folder yes - if you move it or delete it - it's not going to work.
So make sure you place the dll in the folder where you ok for it to stay before registering it.

**Comment by boris-999** [comment]
install instruction #2 was too vague.
install instruction #3 was misleading,  D:/temp  is  not at all a permanent place.

maybe suggest keeping it in C:/Windows/System32  with the other dll's.

**Comment by iOrange** [comment]
It's not an instruction, sorry, I was just showing an example. You can select any folder you prefer.
Since this is not an actual issue of the software, I'll close it.
Thanks!
